### PR TITLE
Add Twrp 3.1.0-0 to zuk z1 

### PR DESCRIPTION
**Pull request by ghost**
there are several new changes in the recovery . you must build a stable one.

### CODE REVIEW

**Comment by bigbiff** [comment]
Please push this to the project at gerrit.twrp.me and add the maintainer as a reviewer.

**Comment by 1510v** [comment]
I dont know how to push the project . can you do it ?

**Comment by ghost** [comment]
I dont know how push the project. can you do this for zuk z1 users.

**Comment by TeamWin-Gerrit** [comment]
Please try reading a gerrit tutorial and let me know if this helps you to
push to our website. We are using all the standard gerrit ports and using
github for authentication.

**Pull request closed without merging**
